version: '3.3'
services:
  mariadb:
    image: 'bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'sql_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'm_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  sql_data:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.10.10.11,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/root/moodle"
  m_data:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.10.10.11,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/root/moodle"
